server:
  port: 8999 # 服务绑定的端口，不写默认是8080
spring:
#  security:
#    user:
#      name: user
#      password: 12345
  datasource:
    driver-class-name:  com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/citizen?characterEncoding=utf8&serverTimezone=GMT%2B8
    username: root
    password: 123456